#!/usr/bin/env python3
"""Production environment setup script with security validation."""
import os
import secrets
import sys
from pathlib import Path
from typing import Dict, List, Tuple


def generate_secret_key(length: int = 32) -> str:
    """Generate a secure random key."""
    return secrets.token_urlsafe(length)


def validate_secret(secret: str, name: str, min_length: int = 32) -> Tuple[bool, str]:
    """Validate that a secret is secure."""
    if not secret or secret.strip() == "":
        return False, f"{name} is empty"
    
    if secret.startswith("CHANGE_ME") or secret.startswith("change-me"):
        return False, f"{name} still has default/placeholder value"
    
    if len(secret) < min_length:
        return False, f"{name} is too short (minimum {min_length} characters)"
    
    # Check for common weak secrets
    weak_secrets = [
        "password", "secret", "key", "12345", "admin", "test",
        "default", "changeme", "production"
    ]
    secret_lower = secret.lower()
    if any(weak in secret_lower for weak in weak_secrets):
        if len(secret) < 50:  # Allow if it's part of a longer secure string
            return False, f"{name} appears to contain common weak patterns"
    
    return True, "OK"


def check_production_security(env_file: Path) -> Tuple[bool, List[str]]:
    """Check production security settings."""
    errors = []
    warnings = []
    
    if not env_file.exists():
        errors.append(f".env file not found at {env_file}")
        return False, errors
    
    # Read environment variables
    env_vars: Dict[str, str] = {}
    with open(env_file, "r") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, value = line.split("=", 1)
                env_vars[key.strip()] = value.strip().strip('"').strip("'")
    
    # Check environment
    environment = env_vars.get("ENVIRONMENT", "development")
    if environment != "production":
        warnings.append(f"ENVIRONMENT is '{environment}', should be 'production'")
    
    # Check debug mode
    debug = env_vars.get("DEBUG", "false").lower()
    if debug == "true":
        errors.append("DEBUG is set to true - MUST be false in production")
    
    # Check secrets
    jwt_secret = env_vars.get("JWT_SECRET_KEY", "")
    is_valid, message = validate_secret(jwt_secret, "JWT_SECRET_KEY", min_length=32)
    if not is_valid:
        errors.append(f"JWT_SECRET_KEY: {message}")
    
    encryption_key = env_vars.get("ENCRYPTION_KEY", "")
    is_valid, message = validate_secret(encryption_key, "ENCRYPTION_KEY", min_length=32)
    if not is_valid:
        errors.append(f"ENCRYPTION_KEY: {message}")
    
    # Check Redis password
    redis_password = env_vars.get("REDIS_PASSWORD", "")
    if not redis_password or redis_password.startswith("CHANGE_ME"):
        errors.append("REDIS_PASSWORD is not set or has default value")
    
    # Check database URL for SSL
    database_url = env_vars.get("DATABASE_URL", "")
    if "sslmode=require" not in database_url and environment == "production":
        warnings.append("DATABASE_URL should include ?sslmode=require for production")
    
    # Check CORS origins
    cors_origins = env_vars.get("CORS_ORIGINS", "")
    if "*" in cors_origins:
        errors.append("CORS_ORIGINS contains '*' - NEVER use wildcards in production")
    if environment == "production" and "localhost" in cors_origins:
        warnings.append("CORS_ORIGINS contains localhost - should use production domains only")
    
    # Check authentication
    require_auth = env_vars.get("REQUIRE_AUTH", "false").lower()
    if environment == "production" and require_auth != "true":
        warnings.append("REQUIRE_AUTH should be 'true' in production")
    
    # Check Celery URLs for Redis password
    celery_broker = env_vars.get("CELERY_BROKER_URL", "")
    celery_backend = env_vars.get("CELERY_RESULT_BACKEND", "")
    if "CHANGE_ME" in celery_broker or "CHANGE_ME" in celery_backend:
        errors.append("CELERY_BROKER_URL or CELERY_RESULT_BACKEND contains placeholder")
    if environment == "production" and (":@" in celery_broker or ":@" in celery_backend):
        # Empty password (redis://:@host) is insecure
        if ":@localhost" in celery_broker or ":@localhost" in celery_backend:
            warnings.append("Celery Redis URLs should use password in production")
    
    return len(errors) == 0, errors + warnings


def create_production_env_template(output_file: Path) -> None:
    """Create a production .env template."""
    template = """# mARB 2.0 - Production Environment Variables
# Generated by setup_production_env.py
# IMPORTANT: Review and update all values before deploying!

# ============================================================================
# ENVIRONMENT CONFIGURATION
# ============================================================================
ENVIRONMENT=production
DEBUG=false

# ============================================================================
# DATABASE CONFIGURATION
# ============================================================================
# PostgreSQL connection string with SSL
# Format: postgresql://user:password@host:port/database?sslmode=require
DATABASE_URL=postgresql://user:password@localhost:5432/marb_risk_engine?sslmode=require
DATABASE_POOL_SIZE=10
DATABASE_MAX_OVERFLOW=20

# ============================================================================
# REDIS CONFIGURATION
# ============================================================================
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD={redis_password}
REDIS_DB=0

# ============================================================================
# SECURITY CONFIGURATION
# ============================================================================
# Generate secure keys with: python generate_keys.py
JWT_SECRET_KEY={jwt_secret}
ENCRYPTION_KEY={encryption_key}
JWT_ALGORITHM=HS256
JWT_ACCESS_TOKEN_EXPIRE_MINUTES=1440
JWT_REFRESH_TOKEN_EXPIRE_DAYS=7
BCRYPT_ROUNDS=12

# ============================================================================
# AUTHENTICATION & AUTHORIZATION
# ============================================================================
REQUIRE_AUTH=true
AUTH_EXEMPT_PATHS=/api/v1/health,/api/v1/docs,/api/v1/openapi.json,/

# ============================================================================
# CORS CONFIGURATION
# ============================================================================
# Replace with your actual production domains
CORS_ORIGINS=https://app.yourdomain.com,https://admin.yourdomain.com

# ============================================================================
# RATE LIMITING
# ============================================================================
RATE_LIMIT_PER_MINUTE=60
RATE_LIMIT_PER_HOUR=1000

# ============================================================================
# CELERY CONFIGURATION
# ============================================================================
CELERY_BROKER_URL=redis://:{redis_password}@localhost:6379/0
CELERY_RESULT_BACKEND=redis://:{redis_password}@localhost:6379/0

# ============================================================================
# LOGGING CONFIGURATION
# ============================================================================
LOG_LEVEL=info
LOG_FORMAT=json
LOG_FILE=app.log
LOG_DIR=logs

# ============================================================================
# CACHE CONFIGURATION
# ============================================================================
CACHE_TTL_RISK_SCORE=3600
CACHE_TTL_CLAIM_DATA=1800
CACHE_TTL_PAYER_RULES=86400
"""
    
    # Generate secure values
    jwt_secret = generate_secret_key(64)
    encryption_key = generate_secret_key(32)
    redis_password = generate_secret_key(32)
    
    content = template.format(
        jwt_secret=jwt_secret,
        encryption_key=encryption_key,
        redis_password=redis_password
    )
    
    with open(output_file, "w") as f:
        f.write(content)
    
    # Set secure permissions (Unix-like systems)
    try:
        os.chmod(output_file, 0o600)
    except OSError:
        pass  # Windows doesn't support chmod the same way


def main():
    """Main function."""
    print("=" * 70)
    print("mARB 2.0 - Production Environment Setup")
    print("=" * 70)
    print()
    
    project_root = Path(__file__).parent.parent
    env_file = project_root / ".env"
    env_example = project_root / ".env.example"
    
    # Check if .env exists
    if env_file.exists():
        print(f"✓ Found existing .env file at {env_file}")
        print()
        print("Checking production security settings...")
        print()
        
        is_secure, issues = check_production_security(env_file)
        
        if is_secure and not issues:
            print("✓ All security checks passed!")
            return 0
        
        # Show errors and warnings
        errors = [i for i in issues if "MUST" in i or "NEVER" in i or not i.startswith("REQUIRE_AUTH")]
        warnings = [i for i in issues if i not in errors]
        
        if errors:
            print("✗ SECURITY ERRORS (must be fixed):")
            for error in errors:
                print(f"  - {error}")
            print()
        
        if warnings:
            print("⚠ WARNINGS (should be fixed for production):")
            for warning in warnings:
                print(f"  - {warning}")
            print()
        
        if errors:
            print("Please fix the errors above before deploying to production.")
            return 1
        else:
            print("Warnings found, but no critical errors.")
            return 0
    else:
        print(f"✗ .env file not found at {env_file}")
        print()
        
        # Check if .env.example exists
        if env_example.exists():
            print(f"✓ Found .env.example template")
            response = input("Create .env from template? (y/N): ").strip().lower()
            if response == "y":
                import shutil
                shutil.copy(env_example, env_file)
                try:
                    os.chmod(env_file, 0o600)
                except OSError:
                    pass
                print(f"✓ Created {env_file}")
                print()
                print("⚠ IMPORTANT: Edit .env and update all placeholder values!")
                print("  - Generate keys: python generate_keys.py")
                print("  - Set REDIS_PASSWORD")
                print("  - Update DATABASE_URL")
                print("  - Set CORS_ORIGINS to production domains")
                print("  - Set REQUIRE_AUTH=true")
                return 0
        else:
            print("Creating production .env template...")
            create_production_env_template(env_file)
            print(f"✓ Created {env_file} with secure defaults")
            print()
            print("⚠ IMPORTANT: Review and update the following:")
            print("  - DATABASE_URL (update with your database credentials)")
            print("  - CORS_ORIGINS (set to your production domains)")
            print("  - All other values have been generated securely")
            return 0


if __name__ == "__main__":
    sys.exit(main())

